version: "3.8"

services:
  db:
    image: postgres:15
    container_name: ai-rag-postgres
    restart: always
    environment:
      POSTGRES_USER: metacoding
      POSTGRES_PASSWORD: metacoding1234
      POSTGRES_DB: metacoding_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
